name: Build and deploy JAR app to Azure Web App - springboot-azure-demo  

on:  
  push:  
    branches:  
      - main  
  workflow_dispatch:  

jobs:  
  build:  
    runs-on: windows-latest  
    permissions:  
      contents: read #This is required for actions/checkout  

    steps:  
      - uses: actions/checkout@v4  

      - name: Set up Java version  
        uses: actions/setup-java@v4  
        with:  
          java-version: '21'  
          distribution: 'microsoft'  

      - name: Build with Maven  
        run: mvn clean install  

      - name: Upload artifact for deployment job  
        uses: actions/upload-artifact@v4  
        with:  
          name: java-app  
          path: '${{ github.workspace }}/target/*.jar'  

  deploy:  
    runs-on: windows-latest  
    needs: build  
    environment:  
      name: 'Production'  
      url: 'https://tarunkotikumar.18' # Change this to your custom URL  
    permissions:  
      id-token: write #This is required for requesting the JWT  
      contents: read #This is required for actions/checkout  

    steps:  
      - name: Download artifact from build job  
        uses: actions/download-artifact@v4  
        with:  
          name: java-app  
      
      - name: Login to Azure  
        uses: azure/login@v2  
        with:  
          client-id: ${{ secrets.__clientidsecretname__ }}  
          tenant-id: ${{ secrets.__tenantidsecretname__ }}  
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}  

      - name: Deploy to Azure Web App  
        id: deploy-to-webapp  
        uses: azure/webapps-deploy@v3  
        with:  
          app-name: 'springboot-azure-demo'  
          slot-name: 'Production'  
          package: '*.jar'  
